import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
from datetime import datetime
import sys
import os
import time

def on_close(event):
    """Handle window X button close"""
    print("Window close button pressed...")
    plt.close('all')
    sys.exit(0)

def plot_performance_data(csv_file, live_mode=True):
    """Plot performance data from CSV file generated by face_identify.py"""
    
    # Setup the figure for live plotting
    fig = plt.figure(figsize=(15, 15))
    gs = gridspec.GridSpec(2, 2, width_ratios=[1.3, 1.0], height_ratios=[1, 1])
    ax1 = fig.add_subplot(gs[0, 0])   # SMA plot
    ax2 = fig.add_subplot(gs[1, 0])   # Distribution plot
    ax3 = fig.add_subplot(gs[:, 1])   # Text panel (spans both rows)
    fig.suptitle(f'Face Recognition Performance Analysis\n{os.path.basename(csv_file).replace(".csv", "").replace("face_recognition_performance_", "")}', fontsize=16)
    
    
    # Connect close event
    fig.canvas.mpl_connect('close_event', on_close)
    
    # Initialize plot lines for live updates
    det_sma_line, = ax1.plot([], [], 'b-', linewidth=2, label='Detection SMA')
    rec_sma_line, = ax1.plot([], [], 'r-', linewidth=2, label='Recognition SMA')
    fps_line, = ax1.plot([], [], 'g-', alpha=0.7, label='FPS')
    ips_line, = ax1.plot([], [], 'y-', alpha=0.7, label='Inferences/Second')
    
    # Setup axes
    ax1.set_title('Time Window Simple Moving Average')
    ax1.set_ylabel('Time (ms)')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    plt.ion()  # Enable interactive mode
    plt.show(block=False)  # Show without blocking
    
    last_modified_time = 0
    update_interval = 5.0  # Update every 3 seconds

    if live_mode:
        print("Starting live performance plotting...")
        print("Press Ctrl+C to stop")

    try:
        while True:
            try:
                # Check if file exists and has been modified
                if os.path.exists(csv_file):
                    current_modified = os.path.getmtime(csv_file)
                    df = pd.read_csv(csv_file)

                    if current_modified <= last_modified_time and live_mode:
                        time.sleep(update_interval)
                        continue
                        
                    if len(df) > 0:
                        # Update SMA plot
                        det_sma_line.set_data(df['Time'], df['Detection_SMA_ms'])
                        rec_sma_line.set_data(df['Time'], df['Recognition_SMA_ms'])
                        fps_line.set_data(df['Time'], df['FPS'])
                        ips_line.set_data(df['Time'], df['Inferences_Per_Second'])
                        
                        # Adjust axes limits
                        if len(df) > 0:
                            x_min, x_max = df['Time'].min(), df['Time'].max()
                            y_min = min(df['Detection_SMA_ms'].min(), df['Recognition_SMA_ms'].min(), df['FPS'].min(), df['Inferences_Per_Second'].min()) * 0.9
                            y_max = max(df['Detection_SMA_ms'].max(), df['Recognition_SMA_ms'].max(), df['FPS'].max(), df['Inferences_Per_Second'].max()) * 1.1
                            
                            ax1.set_xlim(x_min, x_max)
                            ax1.set_ylim(0, max(100, y_max))
                            
                        # Update distribution and stats
                        ax2.clear()
                        ax3.clear()
                        
                        # Distribution plot
                        ax2.hist(df['Detection_SMA_ms'], bins=30, alpha=0.7, color='blue', label='Detection')
                        ax2.hist(df['Recognition_SMA_ms'], bins=30, alpha=0.7, color='red', label='Recognition')
                        ax2.set_title('Performance Distribution')
                        ax2.set_xlabel('Time (ms)')
                        ax2.set_ylabel('Frequency')
                        ax2.legend()
                        ax2.grid(True, alpha=0.3)
                        
                        # Statistics text
                        stats_text = f"""
Detection Statistics:
Mean: {df['Detection_SMA_ms'].mean():.2f}ms
Std:  {df['Detection_SMA_ms'].std():.2f}ms
Min:  {df['Detection_SMA_ms'].min():.2f}ms
Max:  {df['Detection_SMA_ms'].max():.2f}ms

Recognition Statistics:
Mean: {df['Recognition_SMA_ms'].mean():.2f}ms
Std:  {df['Recognition_SMA_ms'].std():.2f}ms
Min:  {df['Recognition_SMA_ms'].min():.2f}ms
Max:  {df['Recognition_SMA_ms'].max():.2f}ms

FPS Statistics:
Current: {df['FPS'].iloc[-1]:.1f}
SMA: {df['FPS_SMA'].mean():.1f}
Std:  {df['FPS_SMA'].std():.1f}
Min:  {df['FPS_SMA'].min():.1f}
Max:  {df['FPS_SMA'].max():.1f}

Inferences Per Second Statistics:
Current: {df['Inferences_Per_Second'].iloc[-1]:.1f}
SMA: {df['Inferences_Per_Second'].mean():.1f}
Std:  {df['Inferences_Per_Second'].std():.1f}
Min:  {df['Inferences_Per_Second'].min():.1f}
Max:  {df['FPS_SMA'].max():.1f}

Total Frames: {df['Frame'].iloc[-1]}
Total Scan Time: {df['Time'].iloc[-1]:.2f}s
Total Avg FPS: {(df['Frame'].iloc[-1]/df['Time'].iloc[-1]):.2f}
Last Update: {datetime.now().strftime('%H:%M:%S')}
"""
                        
                        ax3.text(0.02, 0.98, stats_text, transform=ax3.transAxes, fontsize=12, 
                                fontfamily='serif', va='top', ha='left', wrap=True)
                        ax3.set_title('Performance Summary')
                        ax3.axis('off')
                        
                        # Redraw
                        fig.canvas.draw()
                        fig.canvas.flush_events()
                        
                        last_modified_time = current_modified
                        print(f"Plot updated at {datetime.now().strftime('%H:%M:%S')} with {len(df)} frames")

                if not live_mode:
                    plt.savefig('performance_plot.png')
                    break

                time.sleep(update_interval)

            except Exception as e:
                print(f"Update error: {e}")
                
            for _ in range(int(update_interval) * 10):
                if not live_mode:
                    break
                time.sleep(0.1)
                
    except KeyboardInterrupt:
        print("\nLive plotting stopped by user")
        plt.ioff()  # Turn off interactive mode
        plt.show(block=True)  # Show final plot blocking
        plt.close()

def main():
    # Find most recent CSV file if none specified
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    else:
        # Find most recent CSV file
        csv_files = [f for f in os.listdir('./logs') if f.startswith('face_recognition_performance_') and f.endswith('.csv')]
        if not csv_files:
            print("No performance CSV files found. Run face_identify.py first.")
            return
        
        csv_file = max([".\\logs\\" + f for f in csv_files], key=os.path.getctime)
        print(f"Using most recent file: {csv_file}")
 
    try:
        plot_performance_data(csv_file, live_mode=True)
    except Exception as e:
        print(f"Error: {e}")
    finally:
        print("Plotting application closed")

if __name__ == "__main__":
    main()
